#!/usr/bin/env python3
"""
build-pages.py — Hard Work & Pain static page generator (About / Contact / Updates)

WHAT THIS DOES
Generates three real, standalone, crawlable pages that sit alongside your
blog posts and Platemate page, following the exact same pattern as
build-blog.py:
  1. about/index.html
  2. contact/index.html   (includes a real working contact form via
                            FormSubmit.co — no backend needed)
  3. updates/index.html   (the changelog / "what's new" timeline)

These are separate from the main index.html single-page app. The SPA's
in-page About/Contact/Updates tabs keep working exactly as before for
anyone already on the site — this script just gives each of those sections
a real, independent, indexable URL for search engines and direct links.

HOW TO UPDATE CONTENT
The content for each page lives in the PAGES dict below, as plain HTML
strings (same style as a blog post body — <p>, <h2>, <ul>, etc.). Edit it
there, then run:  python3 build-pages.py

To add a new entry to the Updates timeline, add a new item to the
UPDATES_TIMELINE list (newest entry goes first) and re-run this script.

Sitemap note: sitemap.xml is now generated by build-blog.py (it already
includes /about/, /contact/, and /updates/ alongside your blog posts and
the Platemate page) — this script does NOT touch sitemap.xml, so there's
only one script that owns it and nothing gets silently dropped.

REQUIREMENTS
  Just Python 3, no packages to install. Run from the repo root (the same
  folder that contains index.html and build-blog.py).
"""

import os
from datetime import date

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
SITE_URL = "https://hardworkandpain.com"

# ── PAGE-SPECIFIC BODY CONTENT ────────────────────────────────────────────────

ABOUT_BODY = """
  <section class="about-page-hero">
    <div class="about-page-hero-bg"></div>
    <div class="about-page-hero-content">
      <h1>NO SHORTCUTS.<br><span>NO EXCUSES.</span></h1>
      <p>Hard Work &amp; Pain is a fitness community driving long-term progress through data and discipline. We provide evidence-based training knowledge and the tools required for dedicated lifters who reject hype and clickbait.</p>
    </div>
  </section>

  <section class="the-standard">
    <div class="the-standard-grid">
      <div>
        <h2>The Standard</h2>
        <p class="the-standard-desc">We stand as a gritty, evidence-based alternative to mainstream fitness culture. Progress isn't bought, it's earned through a philosophical commitment to the work.</p>
        <ul class="standard-values-list">
          <li>Discipline</li>
          <li>Data-Driven Progress</li>
          <li>Consistency</li>
          <li>Honesty</li>
          <li>Effort</li>
        </ul>
      </div>
      <div class="standard-image-wrapper">
        <img src="/weight-plates.jpg" alt="Stacked weight plates">
      </div>
    </div>
  </section>

  <div class="values-grid">
    <div class="value-card">
      <div class="value-num">01</div>
      <div class="value-title">Consistency</div>
      <div class="value-desc">Show up. Every single day. Results are built on repetition, not motivation.</div>
    </div>
    <div class="value-card">
      <div class="value-num">02</div>
      <div class="value-title">Honesty</div>
      <div class="value-desc">No shortcuts. No gimmicks. We tell you what actually works, even when it's hard to hear.</div>
    </div>
    <div class="value-card">
      <div class="value-num">03</div>
      <div class="value-title">Progression</div>
      <div class="value-desc">Every session should move you forward. Track it, measure it, own it.</div>
    </div>
    <div class="value-card">
      <div class="value-num">04</div>
      <div class="value-title">Community</div>
      <div class="value-desc">We're all fighting different battles. Respect the grind, support the journey.</div>
    </div>
  </div>
"""

CONTACT_BODY = """
  <div class="contact-wrap">
    <div class="section-eyebrow">Get in touch</div>
    <h1>LET'S <span style="color:var(--gold)">TALK</span></h1>
    <p class="contact-sub">Questions about Platemate, collab ideas, or just want to talk training? Send a message.</p>

    <div class="form-group">
      <label class="form-label">Your Name</label>
      <input class="form-input" type="text" id="contactName" placeholder="First and last name" />
    </div>
    <div class="form-group">
      <label class="form-label">Email</label>
      <input class="form-input" type="email" id="contactEmail" placeholder="your@email.com" />
    </div>
    <div class="form-group">
      <label class="form-label">Subject</label>
      <input class="form-input" type="text" id="contactSubject" placeholder="What's this about?" />
    </div>
    <div class="form-group">
      <label class="form-label">Message</label>
      <textarea class="form-input" id="contactMessage" placeholder="Tell us what's on your mind..."></textarea>
    </div>
    <button class="btn-primary" id="contactSubmitBtn" style="width:100%;font-size:14px;padding:16px" onclick="submitContactForm()">Send Message</button>
    <div id="contactStatus" style="margin-top:16px;font-size:14px;display:none"></div>

    <div class="contact-links">
      <div class="contact-link-card">
        <div class="contact-link-label">App</div>
        <div class="contact-link-value">Platemate PWA</div>
      </div>
      <div class="contact-link-card">
        <div class="contact-link-label">Based In</div>
        <div class="contact-link-value">Chicago, IL</div>
      </div>
    </div>
  </div>
"""

CONTACT_SCRIPT = """
<script>
  function submitContactForm() {
    const name = document.getElementById('contactName').value.trim();
    const email = document.getElementById('contactEmail').value.trim();
    const subject = document.getElementById('contactSubject').value.trim();
    const message = document.getElementById('contactMessage').value.trim();
    const statusEl = document.getElementById('contactStatus');
    const btn = document.getElementById('contactSubmitBtn');

    if (!name || !email || !message) {
      statusEl.style.display = 'block';
      statusEl.style.color = '#e05555';
      statusEl.textContent = 'Please fill in your name, email, and a message.';
      return;
    }

    btn.disabled = true;
    btn.textContent = 'Sending...';
    statusEl.style.display = 'none';

    fetch('https://formsubmit.co/ajax/hardworkandpain@gmail.com', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },
      body: JSON.stringify({
        name: name,
        email: email,
        _subject: subject || 'New message from hardworkandpain.com',
        message: message
      })
    })
      .then(res => res.json())
      .then(() => {
        statusEl.style.display = 'block';
        statusEl.style.color = 'var(--gold)';
        statusEl.textContent = "Message sent \\u2014 we'll get back to you soon.";
        document.getElementById('contactName').value = '';
        document.getElementById('contactEmail').value = '';
        document.getElementById('contactSubject').value = '';
        document.getElementById('contactMessage').value = '';
      })
      .catch(() => {
        statusEl.style.display = 'block';
        statusEl.style.color = '#e05555';
        statusEl.textContent = 'Something went wrong sending your message \\u2014 please try again or email hardworkandpain@gmail.com directly.';
      })
      .finally(() => {
        btn.disabled = false;
        btn.textContent = 'Send Message';
      });
  }
</script>
"""

# Newest entry first.
UPDATES_TIMELINE = [
    {
        "version": "v1.3",
        "date": "July 29, 2026",
        "title": "Nutrition Tracking Arrives",
        "latest": True,
        "items": [
            "New Food tab — log calories, protein, carbs &amp; fat for every day",
            "Food search across a built-in common-foods library, the USDA FoodData Central database, and Open Food Facts for packaged items",
            "Set daily calorie &amp; macro goals and watch progress bars fill in",
            "Log food straight from the main + button on Today, alongside lifts and cardio",
            "Fixed a bug where per-set weights weren't actually saving when editing a logged exercise",
        ],
    },
    {
        "version": "v1.2",
        "date": "July 28, 2026",
        "title": "Shared Templates, Reimagined",
        "latest": False,
        "items": [
            "Renamed Community &#8594; Shared Templates",
            "Search and muscle-group filters when browsing Shared Templates",
            "Like templates you find useful",
            "Add Cardio activities directly inside a template, not just strength exercises",
            "Fixed weight not saving correctly when editing exercises inside a template",
            "Templates now show who created them",
            "Cleaner spacing and layout on template cards",
        ],
    },
    {
        "version": "—",
        "date": "Mid-Late July 2026",
        "title": "Growth, SEO &amp; an Admin Dashboard",
        "latest": False,
        "items": [
            "Converted the blog to real static pages — each post got its own crawlable URL, title, and meta description",
            "Added a repeatable build script so new blog posts take one command instead of hand-built pages",
            "Added Organization, WebSite, and FAQ structured data to help the site actually surface in search",
            "Built an admin dashboard: total users, workout/cardio/template counts, a searchable user table",
            "User profiles now track signup date and last login",
            "Fixed a silent Firestore security rule bug that was affecting Shared Templates",
        ],
    },
    {
        "version": "—",
        "date": "Late June 2026",
        "title": "Hard Work &amp; Pain Launches",
        "latest": False,
        "items": [
            "Built this website — Home, About, Blog, Platemate, and Contact — to give Platemate a real home",
            "Migrated Platemate from Netlify to GitHub Pages for reliable, free hosting",
            "Unified History — lifting and cardio sessions now show together in one chronological timeline",
            "Replaced the old PRs tab with a full Analytics dashboard: streaks, volume trends, a 30-day heatmap, and auto-tracked personal records",
        ],
    },
    {
        "version": "v1.0 – v1.1",
        "date": "Mid-June 2026",
        "title": "The Big Rebuild",
        "latest": False,
        "items": [
            "Rebuilt logging around a real set-by-set system — every set gets its own weight and reps, not just one number per exercise",
            "Full-screen exercise picker with muscle-group filters, replacing a plain text field",
            "Visual dumbbell and barbell plate-loading calculators",
            "Templates arrive — save a routine once, reuse it forever, with early community sharing",
            "Added every Les Mills class and 20+ other cardio activities",
            "Versioned \\u201cwhat's new\\u201d splash screen so updates don't go unnoticed",
            "Forgot-password flow and toast notifications replacing plain browser alerts",
        ],
    },
    {
        "version": "v0.1",
        "date": "June 2026",
        "title": "Day One",
        "latest": False,
        "items": [
            "Platemate is born — a simple exercise and cardio logger, no fluff, built to solve one problem: losing track of your lifts",
            "Firebase Auth and Firestore added so data is never tied to a single browser again",
            "Multi-set support for machine exercises where weight changes set to set",
        ],
    },
]


def build_updates_body():
    entries_html = []
    for e in UPDATES_TIMELINE:
        items_html = "\n".join(f'        <li>{item}</li>' for item in e["items"])
        entry_class = "timeline-entry is-latest" if e["latest"] else "timeline-entry"
        entries_html.append(f"""    <div class="{entry_class}">
      <div class="timeline-meta">
        <span class="timeline-version">{e['version']}</span>
        <span class="timeline-date">{e['date']}</span>
      </div>
      <div class="timeline-title">{e['title']}</div>
      <ul class="timeline-list">
{items_html}
      </ul>
    </div>""")
    return f"""
  <div class="updates-header">
    <h1>THE <span>GRIND</span> LOG</h1>
    <p>Every update to Platemate, from the very first commit to today. No spin, no marketing fluff — just what actually shipped and when.</p>
  </div>

  <div class="timeline">
{chr(10).join(entries_html)}
  </div>
"""


PAGES = {
    "about": {
        "path": "about",
        "title": "About",
        "description": "Hard Work & Pain is a fitness community built for serious lifters. No shortcuts, no hype — just evidence-based training and honest content.",
        "body": ABOUT_BODY,
        "extra_script": "",
        "schema_type": "AboutPage",
    },
    "contact": {
        "path": "contact",
        "title": "Contact",
        "description": "Get in touch with Hard Work & Pain — questions about Platemate, collab ideas, or just want to talk training.",
        "body": CONTACT_BODY,
        "extra_script": CONTACT_SCRIPT,
        "schema_type": "ContactPage",
    },
    "updates": {
        "path": "updates",
        "title": "Updates",
        "description": "Every update to Platemate, from day one to today — new features, fixes, and what's changed.",
        "body": build_updates_body(),
        "extra_script": "",
        "schema_type": "CollectionPage",
    },
}

# ── SHARED PAGE TEMPLATE (matches build-blog.py's post template) ─────────────

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<!-- ══ PRIMARY SEO ══ -->
<title>{title} | Hard Work & Pain</title>
<meta name="description" content="{description}" />
<meta name="keywords" content="Hard Work And Pain, Platemate, workout tracker, fitness community" />
<meta name="author" content="Hard Work & Pain" />
<link rel="canonical" href="{canonical}" />

<!-- ══ OPEN GRAPH ══ -->
<meta property="og:site_name" content="Hard Work & Pain" />
<meta property="og:type" content="website" />
<meta property="og:url" content="{canonical}" />
<meta property="og:title" content="{title} | Hard Work & Pain" />
<meta property="og:description" content="{description}" />
<meta property="og:image" content="{site_url}/og-image.jpg" />

<!-- ══ TWITTER / X CARD ══ -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{title} | Hard Work & Pain" />
<meta name="twitter:description" content="{description}" />
<meta name="twitter:image" content="{site_url}/og-image.jpg" />

<!-- ══ STRUCTURED DATA ══ -->
<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "{schema_type}",
  "name": "{title} | Hard Work & Pain",
  "description": "{description_json}",
  "url": "{canonical}",
  "isPartOf": {{ "@type": "WebSite", "name": "Hard Work & Pain", "url": "{site_url}/" }}
}}
</script>

<link rel="icon" type="image/x-icon" href="/favicon.ico" />
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />

<!-- ══ GOOGLE ANALYTICS ══ -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-TEKMG83C6G"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{dataLayer.push(arguments);}}
  gtag('js', new Date());
  gtag('config', 'G-TEKMG83C6G');
</script>

<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
<style>
  :root {{
    --gold: #FFB612;
    --gold-dim: #cc9200;
    --black: #0a0a0a;
    --dark: #111111;
    --card: #161616;
    --border: #2a2a2a;
    --muted: #888;
    --white: #f0f0f0;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  html {{ scroll-behavior: smooth; }}
  body {{ background: var(--black); color: var(--white); font-family: 'Inter', sans-serif; font-size: 16px; line-height: 1.6; }}

  nav {{
    position: fixed; top: 0; left: 0; right: 0; z-index: 100;
    background: rgba(10,10,10,0.95); backdrop-filter: blur(10px);
    border-bottom: 1px solid var(--border);
    display: flex; align-items: center; justify-content: space-between;
    padding: 0 40px; height: 64px;
  }}
  .nav-logo {{ font-family: 'Bebas Neue', sans-serif; font-size: 26px; color: var(--gold); letter-spacing: 2px; text-decoration: none; }}
  .nav-logo span {{ color: var(--white); }}
  .nav-links {{ display: flex; gap: 32px; list-style: none; }}
  .nav-links a {{ color: var(--muted); text-decoration: none; font-size: 13px; font-weight: 500; letter-spacing: 0.5px; text-transform: uppercase; transition: color 0.2s; }}
  .nav-links a:hover {{ color: var(--gold); }}
  .nav-cta {{ background: var(--gold); color: #000; border: none; padding: 9px 20px; font-size: 13px; font-weight: 700; letter-spacing: 0.5px; text-transform: uppercase; cursor: pointer; text-decoration: none; transition: background 0.2s; }}
  .nav-cta:hover {{ background: var(--gold-dim); }}

  main {{ padding-top: 64px; }}

  .section-eyebrow {{
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 4px;
    text-transform: uppercase;
    color: var(--gold);
    margin-bottom: 16px;
  }}

  /* ── ABOUT PAGE ── */
  .about-page-hero {{
    position: relative;
    min-height: 60vh;
    display: flex;
    align-items: center;
    overflow: hidden;
    border-bottom: 4px solid var(--gold);
  }}
  .about-page-hero-bg {{
    position: absolute;
    inset: 0;
    background-image: url('/about-hero.jpg');
    background-size: cover;
    background-position: center;
  }}
  .about-page-hero-bg::after {{
    content: '';
    position: absolute;
    inset: 0;
    background: linear-gradient(90deg, rgba(10,10,10,0.95) 0%, rgba(10,10,10,0.7) 50%, rgba(10,10,10,0.4) 100%);
  }}
  .about-page-hero-content {{
    position: relative;
    z-index: 2;
    max-width: 800px;
    padding: 80px 40px;
  }}
  .about-page-hero-content h1 {{
    font-family: 'Bebas Neue', sans-serif;
    font-size: clamp(48px, 9vw, 110px);
    letter-spacing: 3px;
    line-height: 0.9;
    color: var(--white);
    text-shadow: 4px 4px 0px var(--black);
    margin-bottom: 0;
  }}
  .about-page-hero-content h1 span {{ color: var(--gold); }}
  .about-page-hero-content p {{
    font-size: 1.1rem;
    color: var(--muted);
    max-width: 600px;
    margin-top: 24px;
    border-left: 3px solid var(--gold);
    padding-left: 16px;
  }}

  .the-standard {{ background-color: var(--card); padding: 100px 40px; }}
  .the-standard-grid {{ max-width: 1100px; margin: 0 auto; display: grid; grid-template-columns: 1fr 1fr; gap: 64px; align-items: center; }}
  .the-standard h2 {{ font-family: 'Bebas Neue', sans-serif; font-size: clamp(40px, 6vw, 72px); color: var(--gold); letter-spacing: 2px; }}
  .the-standard-desc {{ color: var(--muted); margin-top: 16px; max-width: 480px; }}
  .standard-values-list {{ list-style: none; display: flex; flex-direction: column; gap: 20px; margin-top: 40px; padding: 0; }}
  .standard-values-list li {{ font-family: 'Bebas Neue', sans-serif; font-size: 32px; letter-spacing: 1px; color: var(--muted); display: flex; align-items: center; gap: 16px; }}
  .standard-values-list li::before {{ content: ''; display: block; width: 20px; height: 4px; background-color: var(--gold); flex-shrink: 0; }}
  .standard-image-wrapper {{ position: relative; height: 500px; width: 100%; }}
  .standard-image-wrapper img {{ width: 100%; height: 100%; object-fit: cover; filter: grayscale(100%) contrast(1.2); position: relative; z-index: 1; display: block; }}
  .standard-image-wrapper::after {{ content: ''; position: absolute; top: 16px; left: 16px; width: 100%; height: 100%; border: 2px solid var(--gold); z-index: 0; }}

  .values-grid {{ display: flex; flex-wrap: wrap; justify-content: center; gap: 2px; background: transparent; margin: 60px 40px 0; }}
  .value-card {{ background: var(--dark); border: 1px solid var(--border); padding: 40px 28px; flex: 1 1 220px; max-width: 280px; }}
  .value-num {{ font-family: 'Bebas Neue', sans-serif; font-size: 48px; color: var(--gold); opacity: 0.4; line-height: 1; margin-bottom: 12px; }}
  .value-title {{ font-family: 'Bebas Neue', sans-serif; font-size: 22px; letter-spacing: 1px; margin-bottom: 10px; }}
  .value-desc {{ color: var(--muted); font-size: 13px; line-height: 1.7; }}

  /* ── CONTACT PAGE ── */
  .contact-wrap {{ padding: 80px 40px; max-width: 700px; margin: 0 auto; }}
  .contact-wrap h1 {{ font-family: 'Bebas Neue', sans-serif; font-size: clamp(48px, 7vw, 80px); letter-spacing: 3px; line-height: 1; margin-bottom: 12px; }}
  .contact-wrap h1 span {{ color: var(--gold); }}
  .contact-sub {{ color: var(--muted); margin-bottom: 48px; font-size: 15px; }}
  .form-group {{ margin-bottom: 24px; }}
  .form-label {{ display: block; font-size: 11px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: var(--muted); margin-bottom: 8px; }}
  .form-input {{ width: 100%; background: var(--card); border: 1px solid var(--border); color: var(--white); padding: 14px 16px; font-size: 15px; font-family: 'Inter', sans-serif; outline: none; transition: border-color 0.2s; }}
  .form-input:focus {{ border-color: var(--gold); }}
  textarea.form-input {{ resize: vertical; min-height: 140px; }}
  .btn-primary {{ background: var(--gold); color: #000; border: none; padding: 14px 32px; font-size: 14px; font-weight: 700; letter-spacing: 1px; text-transform: uppercase; cursor: pointer; transition: background 0.2s, transform 0.15s; text-decoration: none; display: inline-block; }}
  .btn-primary:hover {{ background: var(--gold-dim); transform: translateY(-1px); }}
  .btn-primary:disabled {{ opacity: 0.6; cursor: default; }}
  .contact-links {{ margin-top: 60px; padding-top: 40px; border-top: 1px solid var(--border); display: grid; grid-template-columns: 1fr 1fr; gap: 2px; background: transparent; }}
  .contact-link-card {{ background: var(--card); border: 1px solid var(--border); padding: 28px 24px; }}
  .contact-link-label {{ font-size: 10px; letter-spacing: 3px; text-transform: uppercase; color: var(--muted); margin-bottom: 8px; }}
  .contact-link-value {{ color: var(--gold); font-size: 15px; font-weight: 500; }}

  /* ── UPDATES PAGE ── */
  .updates-header {{ padding: 80px 40px 48px; max-width: 800px; margin: 0 auto; }}
  .updates-header h1 {{ font-family: 'Bebas Neue', sans-serif; font-size: clamp(48px, 7vw, 80px); letter-spacing: 3px; line-height: 1; }}
  .updates-header h1 span {{ color: var(--gold); }}
  .updates-header p {{ color: var(--muted); margin-top: 16px; font-size: 15px; max-width: 560px; }}
  .timeline {{ max-width: 800px; margin: 0 auto 100px; padding: 0 40px; position: relative; }}
  .timeline::before {{ content: ''; position: absolute; left: 40px; top: 8px; bottom: 8px; width: 2px; background: var(--border); }}
  .timeline-entry {{ position: relative; padding: 0 0 56px 56px; }}
  .timeline-entry:last-child {{ padding-bottom: 0; }}
  .timeline-entry::before {{ content: ''; position: absolute; left: -4px; top: 6px; width: 12px; height: 12px; border-radius: 50%; background: var(--gold); border: 3px solid var(--black); box-shadow: 0 0 0 2px var(--gold); }}
  .timeline-entry.is-latest::before {{ box-shadow: 0 0 0 2px var(--gold), 0 0 14px rgba(255,182,18,0.6); }}
  .timeline-meta {{ display: flex; align-items: center; gap: 12px; margin-bottom: 10px; flex-wrap: wrap; }}
  .timeline-version {{ font-family: 'Bebas Neue', sans-serif; font-size: 22px; letter-spacing: 1px; color: var(--gold); background: var(--card); border: 1px solid var(--border); padding: 2px 14px; border-radius: 20px; }}
  .timeline-date {{ font-size: 11px; color: var(--muted); letter-spacing: 1.5px; text-transform: uppercase; }}
  .timeline-title {{ font-family: 'Bebas Neue', sans-serif; font-size: 26px; letter-spacing: 1px; color: var(--white); margin-bottom: 12px; }}
  .timeline-list {{ list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 8px; }}
  .timeline-list li {{ color: var(--muted); font-size: 14px; line-height: 1.6; padding-left: 20px; position: relative; }}
  .timeline-list li::before {{ content: '\\2192'; position: absolute; left: 0; color: var(--gold); }}

  footer {{ border-top: 1px solid var(--border); padding: 28px 40px; display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 20px; }}
  .footer-logo {{ font-family: 'Bebas Neue', sans-serif; font-size: 22px; color: var(--gold); letter-spacing: 2px; }}
  .footer-logo span {{ color: var(--white); }}
  .footer-copy {{ color: var(--muted); font-size: 12px; }}
  .footer-links {{ display: flex; gap: 24px; }}
  .footer-links a {{ color: var(--muted); text-decoration: none; font-size: 12px; letter-spacing: 1px; text-transform: uppercase; transition: color 0.2s; }}
  .footer-links a:hover {{ color: var(--gold); }}

  @media (max-width: 768px) {{
    nav {{ padding: 0 20px; }}
    .nav-links {{ display: none; }}
    .the-standard-grid {{ grid-template-columns: 1fr; }}
    .standard-image-wrapper {{ height: 320px; }}
    .contact-wrap, .updates-header {{ padding: 60px 20px 40px; }}
    .values-grid {{ margin: 40px 20px 0; }}
    footer {{ flex-direction: column; align-items: flex-start; padding: 28px 20px; }}
  }}
</style>
</head>
<body>

<nav>
  <a href="{site_url}/" class="nav-logo">HARD WORK <span>&amp; PAIN</span></a>
  <ul class="nav-links">
    <li><a href="{site_url}/">Home</a></li>
    <li><a href="{site_url}/about/">About</a></li>
    <li><a href="{site_url}/#blog">Blog</a></li>
    <li><a href="{site_url}/platemate/">Platemate</a></li>
    <li><a href="{site_url}/updates/">Updates</a></li>
    <li><a href="{site_url}/contact/">Contact</a></li>
  </ul>
  <a href="{site_url}/platemate/" class="nav-cta">Get the App</a>
</nav>

<main>
{body}
</main>

<footer>
  <div class="footer-logo">HARD WORK <span>&amp; PAIN</span></div>
  <div class="footer-copy">© {year} Hard Work & Pain. All rights reserved.</div>
  <div class="footer-links">
    <a href="{site_url}/">Home</a>
    <a href="{site_url}/about/">About</a>
    <a href="{site_url}/#blog">Blog</a>
    <a href="{site_url}/platemate/">Platemate</a>
    <a href="{site_url}/updates/">Updates</a>
    <a href="{site_url}/contact/">Contact</a>
  </div>
</footer>
{extra_script}
</body>
</html>
"""


def json_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def build_pages():
    written = []
    for key, page in PAGES.items():
        canonical = f"{SITE_URL}/{page['path']}/"
        html = PAGE_TEMPLATE.format(
            title=page["title"],
            description=page["description"],
            description_json=json_escape(page["description"]),
            canonical=canonical,
            site_url=SITE_URL,
            schema_type=page["schema_type"],
            body=page["body"],
            extra_script=page["extra_script"],
            year=date.today().year,
        )
        out_dir = os.path.join(REPO_ROOT, page["path"])
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, "index.html")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html)
        written.append((page["title"], canonical, out_path))
    return written


def main():
    written = build_pages()
    print(f"Built {len(written)} page(s):")
    for title, url, path in written:
        print(f"  - {title}  ->  {url}")
    print()
    print("Files written (commit/push, or paste into GitHub's web editor):")
    for _, _, path in written:
        print(f"  - {os.path.relpath(path, REPO_ROOT)}")
    print()
    print("Note: sitemap.xml already includes these URLs via build-blog.py —")
    print("no need to touch it here. Re-run build-blog.py if you want to")
    print("refresh the sitemap's lastmod dates.")


if __name__ == "__main__":
    main()
